# Gopkg.toml example
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  name = "github.com/hashicorp/nomad"
  version = "0.10.0"

[[constraint]]
  name = "github.com/docker/app"
  branch = "master"

[[constraint]]
  name = "github.com/docker/docker"
  version = "v19.03.4"
  source = "https://github.com/docker/engine"

[[override]]
  name = "github.com/xeipuuv/gojsonschema"
  revision = "93e72a773fade158921402d6a24c819b48aba29d"

[[override]]
  name = "github.com/docker/distribution"
  revision = "0d3efadf0154c2b8a4e7b6621fff9809655cc580"

[[override]]
  name = "k8s.io/kubernetes"
  revision = "v1.14.1"

[[override]]
  name = "k8s.io/apimachinery"
  revision = "kubernetes-1.14.1"

[[override]]
  name = "k8s.io/api"
  revision = "kubernetes-1.14.1"

[[override]]x
  name = "k8s.io/client-go"
  revision = "kubernetes-1.14.1"

[prune]
  go-tests = true
  unused-packages = true
